
# 连接池配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: 'jdbc:mysql://rm-cn-x0r3or91j001pd4o.rwlb.rds.aliyuncs.com:29165?useSSL=false'
      username: root
      password: Zr13970309103
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  address: 0.0.0.0